#!/bin/sh

rm ./extra_copy/*.cpp

for file in ./*.cpp; do
    fileB=${file##*/}
    fileN=${fileB%.*}
    (echo "// https://open.kattis.com/problems/$fileN" && cat $fileB) > "${fileN}1.cpp" && cp ${fileN}1.cpp "./extra_copy/$file"  && mv "${fileN}1.cpp" "./done/$fileB"
    (echo "// https://open.kattis.com/problems/$fileN" && cat $fileB) > "${fileN}1.cpp" && mv "${fileN}1.cpp" "${fileN}.cpp"
    rm $file ./*.out

done
